name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
      # setup system path for pylint
    - name: Add system path for pylint
      run: echo "export PATH=$PATH:/annotation" >> $GITHUB_ENV
    - name: Analysing the code with pylint within the annotation folder
      run: |
        pylint $(git ls-files 'annotation/*.py')
